### ISSUE TITLE
Add support for NetCDF

### ISSUE THREAD

**Issue by MartinPontius** [GeoNode/geoserver-restconfig#26]
**Is your feature request related to a problem? Please describe.**
I would like to use the library to create NetCDF coverage stores and layers, e.g. with the `create_coveragestore` method.
At the moment this is not possible because the `allowed_types` list doesn't contain this type.

**Describe the solution you'd like**
After adding 'NetCDF' to the `allowed_types` list, the `create_coveragestore` method works with NetCDF files. No other changes were necessary. However, I haven't tested all other functionalities/methods, so there might be more changes necessary for a full support.

**Describe alternatives you've considered**

**Additional context**
In order to use this the Geoserver NetCDF plugin(s) need to be installed.

**Comment by jougisljs** [comment]
I try to use the code : BUT
#####################
cat.create_coveragestore('boa2021031', workspace='cite', type='NetCDF', contet_type='text/xml',
                                  source_name='boa202103',
                                  path=r'file:\test\BOA_Argo_2021_03.nc', layer_name='temp', create_layer=True)
#####################

Traceback (most recent call last):
  File "D:\Python\geoapi\test3.py", line 8, in <module>
    reslut = cat.create_coveragestore('boa2021031', workspace='cite', type='NetCDF', contet_type='text/xml',
  File "C:\Python310\lib\site-packages\geoserver\catalog.py", line 622, in create_coveragestore
    raise FailedRequestError('Failed to create coverage/layer {} for : {}, {}'.format(layer_name, name,
geoserver.catalog.FailedRequestError: Failed to create coverage/layer temp for : boa2021031, 500
